---
title: The Pleistocene-Holocene Transition in Tagua-Tagua, central Chile
author:
  - name: Matías Frugone-Álvarez
    email: matutefrugone@gmail.com
    affiliation: puc
    footnote: 1
  - name: Erwin Gonzáles Huerta
    affiliation: uccs,ciba,geup
  - name: Blas Valero-Garcés
    affiliation: ipe
  - name: Carolina Godoy
    affiliation: uccs,ciba,geup
  - name: Josu Aranbarri
    affiliation: uccs,ciba,geup
  - name: Penélope Gonzáles
    affiliation: iact
  - name: Antonio Delgado-Huerta
    affiliation: uccs,ciba,geup
  - name: Claudio Latorre
    affiliation: deuc
  - name: Rafael Labarca Encina
    affiliation: uccs,ciba,geup
address:
  - code: puc
    address: Pontificia Universidad Católica de Chile, Departamento de Ecología-Centro UC Desierto de Atacama, Av. Libertador Bernardo O'Higgins 340, Santiago, Chile.
  - code: ieb
    address: Instituto de Ecología y Biodiversidady (IEB), Santiago, Chile
  - code: uccs
    address: Instituto Pirenaico de Ecología (IPE-CSIC), Zaragoza, Spain.
  - code: ipe
    address: Centro de Investigación en Biodiversidad y Ambientes Sustentables (CIBAS), Chile 
  - code: geup
    address: Department of Geology and Environmental Science, University of Pittsburgh, Pittsburgh, USA      
  - code: iact
    address: Instituto Andaluz de Ciencias de la Tierra (CSIC-UGR), Granada, Spain  
footnote:
  - code: 1
    text: "Corresponding Author"
abstract: |
  Paleohydrological reconstructions from the Chilean Altiplano document abrupt moisture fluctuations during the last millennia. Although the end of the mid Holocene aridity and the onset of more humid conditions between 6--4 ka has been identified in numerous regional marine and terrestrial sites, the timing of late Holocene dry and humid phases shows large regional variability. Laguna Miscanti and Laguna Miñiques (23$^\circ$ 43'S -- 67$^\circ$ 46'W, 4140 m asl) are topographically closed, but connected by surface outflow from Miscanti. Sedimentological and geochemical indicators from two new cores show large facies changes, i.e. higher carbonate and evaporite deposition during more arid periods and increased organic productivity (both algal and macrophyte) during more humid phases. As in most Andean lakes located in volcanic settings, large 14C reservoir effects occur complicating 14C dating, so the age models include 210Pb and U/Th dating. In spite of dating uncertainties, both lakes show similar patterns during the last millennium. A humid phase in Laguna Miscanti prior to ca 1200 CE is coherent with rodent middens and geomorphological features indicative of a major pluvial/recharge event at lower altitudes (Atacama Desert) during the Medieval Climate Anomaly (ca 800 - 1300 CE). The LIA (1300 – 1850 CE) is characterized by several arid/humid cycles and the last century by a productivity increase. The hydrological changes observed during the last millennium illustrate the complex dynamics of recent climate evolution over the high altitude Andean plateau. Discrepancies between the northern and southern Altiplano records and with intermediate latitudes (Central Chile) records may reflect contrasting responses to external forcing (Westerlies versus South American Monsoon dynamics) along different climatic zones.
  
keywords: "keywords"
journal: "Quaternary Science Reviews"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
linenumbers: true
numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
editor_options: 
  markdown: 
    wrap: 72
---

*Text based on elsarticle sample manuscript, see
<http://www.elsevier.com/author-schemas/latex-instructions#elsarticle>*


# Introduction

# Study site and regional setting

# Materials and methods

## Sedimentary and geochemical analysis


In Dicembre 2013, we recovered 5 cores sediment at several sites around to Tagua Tagua 3 site using sing a hammer-modified UWITEC gravity corer and a UWITEC platform (Fig. 1 and Table S1). The cores were transported to the IACT-CSIC (Granada) and IPE-CSIC (Zaragoza-Jaca) laboratories in Spain for image acquisition and measurement of sediment physical properties, density and Magnetic Susceptibility (MS [x10$^{-8}$ $(m^3/kg)$]) 

at 1 cm resolution, with a Geotek Multi-Sensor Core Logger (MSCL). Elemental geochemical analyses were performed every 1 cm for total carbon (TC), total inorganic carbon (TIC), total organic carbon (TOC=TC-TIC) and total sulfur (TS) in a LECO SC 144 DR furnace (IPE-CSIC). Total nitrogen (TN) was measured in a VARIO MAX CN elemental analyzer (IPE-CSIC). Grain-size distributions between 0.02 μm and 2000 μm were measured using a Malvern Mastersizer 2000 APA2000 grain-size analyzer with Hydro 2000G AWA2000. Sedimentary facies were described based on criteria formulated by [@schnurrenbergerClassificationLacustrineSediments2003] and lacustrine units have been classified according to the  sedimentary structure,MSCL data,  elemental composition (TOC, TIC, TN, TS, TOC/TN, BioSi),  XRF data and waxes composition. 


## Chronology

The chronology for the Miscanti (MIS13-2A) and Miñique (MIN13-1F) sequence was obtained using ${^{210}{Pb}}$ and ${^{137}{Cs}}$ dating techniques, eight U/Th dates and, nine ${^{14}{C}}$ AMS dates (see Table 1). Core MIN13-1F-1G was sampled in the field every 0.5 and 1 cm for ${^{210}{Pb}}$ and ${^{137}{Cs}}$. The MIS13-2A-1G sequence was correlated with the ${^{210}{Pb}}$ and ${^{137}{Cs}}$ data from the sequence obtained by Valero-Garcés et al., 1996. The radiocarbon ages were determined in MIS13-2A-1G and MIN13-1F-1G cores by AMS at Poznan Radiocarbon Laboratory, Poland and the DirectAMS laboratories, USA. Waters from the hypolimnion has also sampled to assess modern ${^{14}{C}}$ reservoir effects (Table  1). The U/Th dating was done at the Massachusetts Institute of Technology (MIT, McGee Lab). For U/Th samples, the cores were visually assessed for material to dating criteria and methods described in [@chenUThDatingLake2020; @lawrenceedwards238U234U230Th232ThSystematicsPrecise1987; @shenUraniumThoriumIsotopic2002]. A VG PQ2+ quadrupole ICP-MS and an Agilent 7900 ICP-MS at MIT was using to determined uranium and thorium concentration. Samples with higher U/Th ratios were then identified as materials worth further processing as they are more likely to yield “clean” samples with high ${^{230}{Th}}$/${^{232}{Th}}$ ratios. The isotopic compositions of the resulting uranium and thorium fractions were then measured on a Nu Plasma II-ES multi-collector ICP-MS at MIT. 

## Data analysis

# Results



## Cores correlations and sedimentary proxies


# References {#references .unnumbered}
